// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Todo struct {
	ID          int64
	Description string
	Status      string
	DueDate     sql.NullString
	CreatedAt   string
}
