// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (description, status, due_date)
VALUES (?1, ?2, ?3)
RETURNING id, description, status, due_date, created_at
`

type CreateTodoParams struct {
	Description string
	Status      string
	DueDate     sql.NullString
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Description, arg.Status, arg.DueDate)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ?1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const listTodos = `-- name: ListTodos :many
SELECT id, description, status, due_date, created_at
FROM todos
WHERE
    CASE WHEN ?1 THEN status = ?2 ELSE true END
    AND CASE WHEN ?3 != '' THEN true ELSE true END
ORDER BY
    CASE ?3
        WHEN 'description' THEN description
        WHEN 'due_date' THEN due_date
        ELSE created_at
    END ASC
`

type ListTodosParams struct {
	ByStatus  interface{}
	Status    string
	SortField interface{}
}

func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, arg.ByStatus, arg.Status, arg.SortField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTodoStatus = `-- name: ToggleTodoStatus :one
UPDATE todos
SET status = CASE WHEN status = 'done' THEN 'todo' ELSE 'done' END
WHERE id = ?1
RETURNING id, description, status, due_date, created_at
`

func (q *Queries) ToggleTodoStatus(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, toggleTodoStatus, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}
